CREATE DATABASE atm;
USE atm;

DROP TABLE t_user;
DROP TABLE t_board;

CREATE TABLE t_user (
   i_user INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   upw VARCHAR(20) NOT NULL,
   nm VARCHAR(20) NOT NULL,
   email VARCHAR(30) UNIQUE NOT NULL,
   intro VARCHAR(100),
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   profile_img VARCHAR(100)
);

CREATE TABLE t_board(
   i_board INT UNSIGNED AUTO_INCREMENT,
   PRIMARY KEY(i_board),
   question VARCHAR(2000) NOT NULL,
   answer VARCHAR(2000),
   i_user INT UNSIGNED NOT NULL,
   que_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   ans_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   ansmod_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   foreign KEY(i_user) REFERENCES t_user(i_user)
);atm